name: Check Protected Files on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@v44

      - name: Fail if protected files modified
        run: |
          protected_files=(
            "Jenkinsfile"
            "MyApplication/nlog.config"
          )
          for file in "${protected_files[@]}"; do
            if echo "${{ steps.changes.outputs.all_changed_files }}" | grep -qw "$file"; then
              echo "Error: Protected file '$file' was modified."
              exit 1
            fi
          done
